# Create a new user
POST http://localhost:3336/api/auth/user HTTP/1.1
Content-Type: application/json

{
  "name": "Keks",
  "email": "user41@test.com",
  "city": "Москва",
  "birthDate": "1980-11-02",
  "password": "123456",
  "role": "Contractor"
}

###

# Get user by ID
GET http://localhost:3336/api/auth/user/63bd0a90f21de8ef1e51c551 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3336/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user40@test.com",
  "password": "123456"
}

###

# Refresh auth token
POST http://localhost:3336/api/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JiZjg3MjgwZWQxN2ZiYTdkN2ViYWQiLCJlbWFpbCI6InVzZXIyNUB0ZXN0LmNvbSIsInJvbGUiOiJDb250cmFjdG9yIiwibmFtZSI6Ik5vdEtla3MiLCJpYXQiOjE2NzMyNjU0NjQsImV4cCI6MTY3Mzg3MDI2NH0.Qb8rfpSqM1z045oTBzBzVcXgdIygzVBJ8u1Nzkgfcz0

###

# Update user data
PATCH http://localhost:3336/api/auth/user/63bd0a90f21de8ef1e51c551 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkMGE5MGYyMWRlOGVmMWU1MWM1NTEiLCJlbWFpbCI6InVzZXI0MUB0ZXN0LmNvbSIsInJvbGUiOiJDb250cmFjdG9yIiwibmFtZSI6Iktla3MiLCJpYXQiOjE2NzMzMzM3MDcsImV4cCI6MTY3MzMzNzMwN30.jEORKl23LDjniwwreRDBBmHHQyX3PDk9eY1yuP139fU

{
  "name": "NotKeks",
  "description": "I liiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiike cats!",
  "skills": ["reading", "gaming","react", "gaming"]
}

###

# Change password
PUT http://localhost:3336/api/auth/user/63bbf87280ed17fba7d7ebad/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JiZjg3MjgwZWQxN2ZiYTdkN2ViYWQiLCJlbWFpbCI6InVzZXIyNUB0ZXN0LmNvbSIsInJvbGUiOiJDb250cmFjdG9yIiwibmFtZSI6Ik5vdEtla3MiLCJpYXQiOjE2NzMyNjUwMTIsImV4cCI6MTY3MzI2ODYxMn0.TpQfRbiuXHy2HKIuaXqjpNM3-3u0bk-dzaDtadFHeK8

{
  "oldPassword": "1234567",
  "newPassword": "123456"
}

###

# Upload avatar
POST http://localhost:3336/api/auth/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JiZjg3MjgwZWQxN2ZiYTdkN2ViYWQiLCJlbWFpbCI6InVzZXIyNUB0ZXN0LmNvbSIsInJvbGUiOiJDb250cmFjdG9yIiwibmFtZSI6Ik5vdEtla3MiLCJpYXQiOjE2NzMyNjUwMTIsImV4cCI6MTY3MzI2ODYxMn0.TpQfRbiuXHy2HKIuaXqjpNM3-3u0bk-dzaDtadFHeK8

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpeg

< avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Create a new task
POST http://localhost:3336/api/tasks/task HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkMGE3OGYyMWRlOGVmMWU1MWM1NGQiLCJlbWFpbCI6InVzZXI0MEB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJOb3RLZWtzIiwiaWF0IjoxNjczMzMzNzg0LCJleHAiOjE2NzMzMzczODR9.k_xkpjVIlkUvIZ3a4MO1A1upvwgvMJzZ5T5b8Xdtplg

{
  "title": "Task's title veeeeeeeeeeeeeery long",
  "description": "Task's description Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla ",
  "categoryId": 1,
  "price": 100,
  "dueDate": "2023-01-10",
  "city": "Санкт-Петербург",
  "tags": ["tag1", "TAG2", "tag2"]
}

###

# Update task data
PATCH http://localhost:3336/api/tasks/task/7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkMGE3OGYyMWRlOGVmMWU1MWM1NGQiLCJlbWFpbCI6InVzZXI0MEB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJOb3RLZWtzIiwiaWF0IjoxNjczMzMzNzg0LCJleHAiOjE2NzMzMzczODR9.k_xkpjVIlkUvIZ3a4MO1A1upvwgvMJzZ5T5b8Xdtplg

{
  "title": "Not Task's title veeeeeeeeeeeeeery long",
  "description": "Not Task's description Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla ",
  "tags": ["tag1", "TAG2", "tag2"]
}

###

# Upload task image
POST http://localhost:3336/api/tasks/task/6/image HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I3YzdjNTc3OGMzNTJhOWYyZTM2Y2IiLCJlbWFpbCI6InVzZXIyQHRlc3QuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6Iktla3MiLCJpYXQiOjE2NzMyNzQxMjUsImV4cCI6MTY3MzI3NzcyNX0.vVY4ZUPTJisAaqS-edcf7Ojep-GL-FHpswocyQULyQc

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Change task's status
PATCH http://localhost:3336/api/tasks/task/7/status HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkMGE3OGYyMWRlOGVmMWU1MWM1NGQiLCJlbWFpbCI6InVzZXI0MEB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJOb3RLZWtzIiwiaWF0IjoxNjczMzM0ODI0LCJleHAiOjE2NzMzMzg0MjR9.RCi7wk0J5AFNTWCxi6mvHe5DUMtNnC4tQl8aVWJI7tE

{
  "command": "done",
  "contractor": "63bd0a90f21de8ef1e51c551"
}

###

# Get task by ID
GET http://localhost:3336/api/tasks/task/6 HTTP/1.1

###

# Delete task by Id
DELETE http://localhost:3336/api/tasks/task/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I3YzdjNTc3OGMzNTJhOWYyZTM2Y2IiLCJlbWFpbCI6InVzZXIyQHRlc3QuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6Iktla3MiLCJpYXQiOjE2NzMyNzQxMjUsImV4cCI6MTY3MzI3NzcyNX0.vVY4ZUPTJisAaqS-edcf7Ojep-GL-FHpswocyQULyQc

###

# Get new tasks
GET http://localhost:3336/api/tasks/new  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JiZjg3MjgwZWQxN2ZiYTdkN2ViYWQiLCJlbWFpbCI6InVzZXIyNUB0ZXN0LmNvbSIsInJvbGUiOiJDb250cmFjdG9yIiwibmFtZSI6Ik5vdEtla3MiLCJpYXQiOjE2NzMyNzI5MzksImV4cCI6MTY3MzI3NjUzOX0.5Ug86yczwIE92F8a_b_MmS7-Ijzf1--5RDEWdMBsHUc

###

# Get new tasks
GET http://localhost:3336/api/tasks/new?categories=2,1&limit=2&page=1&sort=popular  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JiZjg3MjgwZWQxN2ZiYTdkN2ViYWQiLCJlbWFpbCI6InVzZXIyNUB0ZXN0LmNvbSIsInJvbGUiOiJDb250cmFjdG9yIiwibmFtZSI6Ik5vdEtla3MiLCJpYXQiOjE2NzMyNzI5MzksImV4cCI6MTY3MzI3NjUzOX0.5Ug86yczwIE92F8a_b_MmS7-Ijzf1--5RDEWdMBsHUc

###

# Get personal tasks
GET http://localhost:3336/api/tasks/personal?statuses=new,done HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I3YzdjNTc3OGMzNTJhOWYyZTM2Y2IiLCJlbWFpbCI6InVzZXIyQHRlc3QuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6Iktla3MiLCJpYXQiOjE2NzMyNzQxMjUsImV4cCI6MTY3MzI3NzcyNX0.vVY4ZUPTJisAaqS-edcf7Ojep-GL-FHpswocyQULyQc

###

# Add comment to task
POST http://localhost:3336/api/tasks/task/7/comment HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkMGE3OGYyMWRlOGVmMWU1MWM1NGQiLCJlbWFpbCI6InVzZXI0MEB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJOb3RLZWtzIiwiaWF0IjoxNjczMzMzNzg0LCJleHAiOjE2NzMzMzczODR9.k_xkpjVIlkUvIZ3a4MO1A1upvwgvMJzZ5T5b8Xdtplg

{
  "text": "Nice comment text!"
}

###

# Get task comments
GET http://localhost:3336/api/tasks/task/7/comment HTTP/1.1

###

# Get task comments with pagination
GET http://localhost:3336/api/tasks/task/7/comment?limit=1&page=1 HTTP/1.1

###

# Delete comment
DELETE http://localhost:3336/api/tasks/task/7/comment/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkMGE3OGYyMWRlOGVmMWU1MWM1NGQiLCJlbWFpbCI6InVzZXI0MEB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJOb3RLZWtzIiwiaWF0IjoxNjczMzMzNzg0LCJleHAiOjE2NzMzMzczODR9.k_xkpjVIlkUvIZ3a4MO1A1upvwgvMJzZ5T5b8Xdtplg

###


# Create new category
POST http://localhost:3336/api/tasks/category HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkMGE3OGYyMWRlOGVmMWU1MWM1NGQiLCJlbWFpbCI6InVzZXI0MEB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJOb3RLZWtzIiwiaWF0IjoxNjczMzMzNzg0LCJleHAiOjE2NzMzMzczODR9.k_xkpjVIlkUvIZ3a4MO1A1upvwgvMJzZ5T5b8Xdtplg

{
  "name": "reacting"
}

###

# Get all categories
GET http://localhost:3336/api/tasks/category HTTP/1.1

###

# Create new contractor's response
POST http://localhost:3336/api/tasks/task/7/response HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkMGE5MGYyMWRlOGVmMWU1MWM1NTEiLCJlbWFpbCI6InVzZXI0MUB0ZXN0LmNvbSIsInJvbGUiOiJDb250cmFjdG9yIiwibmFtZSI6Ik5vdEtla3MiLCJpYXQiOjE2NzMzMzQ3NTksImV4cCI6MTY3MzMzODM1OX0.c1dIgJvN7O7j-LfctPUTN4_kjbqgIA1X_VOPh5laSgw

###

# Get all responses by task
GET http://localhost:3336/api/tasks/task/7/response HTTP/1.1

###

# Add review to task
POST http://localhost:3336/api/tasks/task/7/review HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkMGE3OGYyMWRlOGVmMWU1MWM1NGQiLCJlbWFpbCI6InVzZXI0MEB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJOb3RLZWtzIiwiaWF0IjoxNjczMzM0ODI0LCJleHAiOjE2NzMzMzg0MjR9.RCi7wk0J5AFNTWCxi6mvHe5DUMtNnC4tQl8aVWJI7tE

{
  "text": "Nice doooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooone!",
  "contractor": "63bd0a90f21de8ef1e51c551",
  "rating": 5
}

###
