# Create a new user
POST http://localhost:3334/api/auth/user HTTP/1.1
Content-Type: application/json

{
  "name": "Keks",
  "email": "user23@test.com",
  "city": "Москва",
  "birthDate": "1980-11-02",
  "password": "123456",
  "role": "Contractor"
}

###

# Update user data
PATCH http://localhost:3334/api/auth/user/63b98c9ca575a1c6ae08abdd HTTP/1.1
Content-Type: application/json
Authorization: Bearer {token}

{
  "name": "NotKeks",
  "description": "I liiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiike cats!",
  "skills": ["reading", "gaming","react", "gaming"]
}

###

# Change password
PUT http://localhost:3334/api/auth/user/639c11a0d451cf0460d5bd38/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {token}

{
  "oldPassword": "123456",
  "newPassword": "1234567"
}

###

# Get user by ID
GET http://localhost:3334/api/auth/user/63b7c7c5778c352a9f2e36cb HTTP/1.1

###

# Login user by email and password
POST http://localhost:3334/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user22@test.com",
  "password": "123456"
}

###

# Refresh auth token
POST http://localhost:3334/api/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer {token}

###

# Upload avatar
POST http://localhost:3334/api/auth/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {token}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpeg

< avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# download avatar
GET http://localhost:3334/static/D_VLTjkQxfo4VIUzjCvYx.jpeg HTTP/1.1

###
