# Create a new user
POST http://localhost:3334/api/auth/user HTTP/1.1
Content-Type: application/json

{
  "name": "Keks",
  "email": "user@test.com",
  "city": "Москва",
  "birthDate": "2012-02-22",
  "password": "123456",
  "role": "Customer"
}

###

# Update user data
PATCH http://localhost:3334/api/auth/user/639c11a0d451cf0460d5bd38 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzljMTFhMGQ0NTFjZjA0NjBkNWJkMzgiLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6Ik5vdEtla3MxMSIsImlhdCI6MTY3MjgzODIwMiwiZXhwIjoxNjcyODM4MjYyfQ.Ycs0orGUftSv8grd_YV_Do6MN_LHhaPyQN2qZ1HpqsA

{
  "name": "NotKeks"
}

###

# Change password
PUT http://localhost:3334/api/auth/user/639c11a0d451cf0460d5bd38/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzljMTFhMGQ0NTFjZjA0NjBkNWJkMzgiLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6Ik5vdEtla3MxMSIsImlhdCI6MTY3MjgzODIwMiwiZXhwIjoxNjcyODM4MjYyfQ.Ycs0orGUftSv8grd_YV_Do6MN_LHhaPyQN2qZ1HpqsA

{
  "oldPassword": "123456",
  "newPassword": "1234567"
}

###

# Get user by ID
GET http://localhost:3334/api/auth/user/63b7c7c5778c352a9f2e36cb HTTP/1.1

###

# Login user by email and password
POST http://localhost:3334/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user1@test.com",
  "password": "123456"
}

###

# Refresh auth token
POST http://localhost:3334/api/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzljMTFhMGQ0NTFjZjA0NjBkNWJkMzgiLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6Ik5vdEtla3MiLCJpYXQiOjE2NzExNzc5NDgsImV4cCI6MTY3MTc4Mjc0OH0.yc1LmgUWJzVHm7wVzd63R-ZXjSsfYvJhAsOoOu5-hCI

###

# Upload avatar
POST http://localhost:3334/api/auth/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzljMTFhMGQ0NTFjZjA0NjBkNWJkMzgiLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6Ik5vdEtla3MiLCJpYXQiOjE2NzI4NDAxODEsImV4cCI6MTY3Mjg0MDI0MX0.GQh_EMEaaCKUF_QtlWlvdD3Hip6SIYEjp73mcD2wUaA

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpeg

< avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# download avatar
GET http://localhost:3334/static/D_VLTjkQxfo4VIUzjCvYx.jpeg HTTP/1.1

###
