# Create a new user
POST http://localhost:3334/api/auth/user HTTP/1.1
Content-Type: application/json

{
  "name": "Keks",
  "email": "user7@notfound.local",
  "city": "Москва",
  "birthDate": "2012-02-22",
  "password": "123456",
  "role": "Contractor"
}

###

# Update user data
PATCH http://localhost:3334/api/auth/user/639c11a0d451cf0460d5bd38 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzljMTFhMGQ0NTFjZjA0NjBkNWJkMzgiLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6Ik5vdEtla3MiLCJpYXQiOjE2NzExNzgxMDMsImV4cCI6MTY3MTE3ODE2M30.mn9dyGNtzmRTtUTlAR7hDAKFZRwHN6ZKehUJSIu5Zis

{
  "name": "NotKeks"
}

###

# Change password
PUT http://localhost:3334/api/auth/user/639c11a0d451cf0460d5bd38/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzljMTFhMGQ0NTFjZjA0NjBkNWJkMzgiLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6Iktla3MiLCJpYXQiOjE2NzExNzI4NTEsImV4cCI6MTY3MTE3MjkxMX0.5EzZHvkmpwsr6hMGyNUNUj0N9CO81ifwBPZAx7A-JyA

{
  "oldPassword": "123456",
  "newPassword": "1234567"
}

###

# Get user by ID
GET http://localhost:3334/api/auth/user/639c11a0d451cf0460d5bd38 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3334/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user1@notfound.local",
  "password": "123456"
}

###

# Refresh auth token
POST http://localhost:3334/api/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzljMTFhMGQ0NTFjZjA0NjBkNWJkMzgiLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6Ik5vdEtla3MiLCJpYXQiOjE2NzExNzc5NDgsImV4cCI6MTY3MTc4Mjc0OH0.yc1LmgUWJzVHm7wVzd63R-ZXjSsfYvJhAsOoOu5-hCI

###
