# Create a new task
POST http://localhost:3335/api/tasks/task HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JhN2IxZGE5OWUzMjYyNThmMmVhNjMiLCJlbWFpbCI6InVzZXIyMkB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjczMTY3NDc4LCJleHAiOjE2NzMxNzEwNzh9.44Osg2UDEBID1P_LG7oUFaM_VKFv91KUKMTaAr_Zg7Q

{
  "title": "Task's title veeeeeeeeeeeeeery long",
  "description": "Task's description Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla ",
  "categoryId": 1,
  "price": 100,
  "dueDate": "2023-01-10",
  "city": "Санкт-Петербург",
  "tags": ["tag1", "TAG2", "tag2"]
}

###

# Update task data
PATCH http://localhost:3335/api/tasks/task/32 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JhN2IxZGE5OWUzMjYyNThmMmVhNjMiLCJlbWFpbCI6InVzZXIyMkB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjczMTY1NjI0LCJleHAiOjE2NzMxNjkyMjR9.QfKxZ25_gYaZzfikVZJmQ6rSP-hnsqCm6iJ5vCMbQqc

{
  "title": "Not Task's title veeeeeeeeeeeeeery long",
  "description": "Not Task's description Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla ",
  "tags": ["tag1", "TAG2", "tag2"]
}

###

# Get task by ID
GET http://localhost:3335/api/tasks/task/34 HTTP/1.1

###

# Delete task by Id
DELETE http://localhost:3335/api/tasks/task/32 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JhN2IxZGE5OWUzMjYyNThmMmVhNjMiLCJlbWFpbCI6InVzZXIyMkB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjczMTY1NjI0LCJleHAiOjE2NzMxNjkyMjR9.QfKxZ25_gYaZzfikVZJmQ6rSP-hnsqCm6iJ5vCMbQqc

###

# Get new tasks
GET http://localhost:3335/api/tasks/new HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I4MjA2YTkwZDRjMDA3YTNkYWI2YWIiLCJlbWFpbCI6InVzZXIzQHRlc3QuY29tIiwicm9sZSI6IkNvbnRyYWN0b3IiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY3MzA3MzI5NCwiZXhwIjoxNjczMDc2ODk0fQ.8pA-kDBy2vifuqCXPb0CEXrlTlFNj8OZB6Y8DTkCAtA

###

# Get new tasks (filtered by categories, sorted and with pagination)
GET http://localhost:3335/api/tasks/new?categories=2,1&limit=2&page=1&sort=popular HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I3YzdhMTc3OGMzNTJhOWYyZTM2YzciLCJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwicm9sZSI6IkNvbnRyYWN0b3IiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY3Mjk4OTg5MCwiZXhwIjoxNjcyOTkzNDkwfQ.As2QjuaJCrlSP8AmnZNLbVYo_9IdHoEJZNRRc8mAFtM

###

# Get new tasks (filtered by cities)
GET http://localhost:3335/api/tasks/new?cities=Москва HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I3YzdhMTc3OGMzNTJhOWYyZTM2YzciLCJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwicm9sZSI6IkNvbnRyYWN0b3IiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY3Mjk4OTg5MCwiZXhwIjoxNjcyOTkzNDkwfQ.As2QjuaJCrlSP8AmnZNLbVYo_9IdHoEJZNRRc8mAFtM

###

# Get new tasks (filtered by tags)
GET http://localhost:3335/api/tasks/new?tags=cleaning HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I5MmUxNjhjNWM2ODNhMzkxOGFkY2QiLCJlbWFpbCI6InVzZXIxMkB0ZXN0LmNvbSIsInJvbGUiOiJDb250cmFjdG9yIiwibmFtZSI6Ik5vdEtla3MiLCJpYXQiOjE2NzMwOTIwMzUsImV4cCI6MTY3MzA5NTYzNX0.9zeFkllvi5shP47vxRhSVKRXflT4cxOOAm0ecmtuQMg
###

# Get personal tasks
GET http://localhost:3335/api/tasks/personal HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JhN2IxZGE5OWUzMjYyNThmMmVhNjMiLCJlbWFpbCI6InVzZXIyMkB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjczMTY1NjI0LCJleHAiOjE2NzMxNjkyMjR9.QfKxZ25_gYaZzfikVZJmQ6rSP-hnsqCm6iJ5vCMbQqc

###

# Change task's status
PATCH http://localhost:3335/api/tasks/task/34/status HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JhN2IxZGE5OWUzMjYyNThmMmVhNjMiLCJlbWFpbCI6InVzZXIyMkB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjczMTcxMTQzLCJleHAiOjE2NzMxNzQ3NDN9.HFbNiCjep6lffPqYHIzGJEFQVAPBWTn1bZRIsNn4OnQ

{
  "command": "start",
  "contractor": "63ba8f0aa99e326258f2ea6a"
}

###

# Add comment to task
POST http://localhost:3335/api/tasks/task/34/comment HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JhN2IxZGE5OWUzMjYyNThmMmVhNjMiLCJlbWFpbCI6InVzZXIyMkB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjczMTY3NDc4LCJleHAiOjE2NzMxNzEwNzh9.44Osg2UDEBID1P_LG7oUFaM_VKFv91KUKMTaAr_Zg7Q

{
  "text": "Nice comment text!"
}

###

# Delete comment
DELETE http://localhost:3335/api/tasks/task/34/comment/10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JhN2IxZGE5OWUzMjYyNThmMmVhNjMiLCJlbWFpbCI6InVzZXIyMkB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjczMTY3NDc4LCJleHAiOjE2NzMxNzEwNzh9.44Osg2UDEBID1P_LG7oUFaM_VKFv91KUKMTaAr_Zg7Q

###

# Get comments by task
GET http://localhost:3335/api/tasks/task/34/comment HTTP/1.1

###

# Get comments by task with pagination
GET http://localhost:3335/api/tasks/task/14/comment?limit=1&page=1 HTTP/1.1

###

# Create new category
POST http://localhost:3335/api/tasks/category HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JhN2IxZGE5OWUzMjYyNThmMmVhNjMiLCJlbWFpbCI6InVzZXIyMkB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjczMTY3NDc4LCJleHAiOjE2NzMxNzEwNzh9.44Osg2UDEBID1P_LG7oUFaM_VKFv91KUKMTaAr_Zg7Q

{
  "name": "gaming"
}

###

# Get all categories
GET http://localhost:3335/api/tasks/category HTTP/1.1

###

# Create new contractor's response
POST http://localhost:3335/api/tasks/task/34/response HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JhOGYwYWE5OWUzMjYyNThmMmVhNmEiLCJlbWFpbCI6InVzZXIyM0B0ZXN0LmNvbSIsInJvbGUiOiJDb250cmFjdG9yIiwibmFtZSI6Iktla3MiLCJpYXQiOjE2NzMxNzA3MzIsImV4cCI6MTY3MzE3NDMzMn0.6HWvlXIcCu2AW7ABPTpGZanoFJDL15NOAGyt9de5_yo

###

# Get all responses by task
GET http://localhost:3335/api/tasks/task/34/response HTTP/1.1

###

# Add review to task
POST http://localhost:3335/api/tasks/task/34/review HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JhN2IxZGE5OWUzMjYyNThmMmVhNjMiLCJlbWFpbCI6InVzZXIyMkB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjczMTcxNTYxLCJleHAiOjE2NzMxNzUxNjF9.VZzNBhXkuIRJ5URdBrWqHJM0ltJ6ovENI0wVauYCcQY

{
  "text": "Nice doooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooone!",
  "contractor": "63ba8f0aa99e326258f2ea6a",
  "rating": 5
}

###

# Get task contractor data
GET http://localhost:3335/api/tasks/contractor/63ba8f0aa99e326258f2ea6a HTTP/1.1

###

# Get task customer data
GET http://localhost:3335/api/tasks/customer/63b7c7c5778c352a9f2e36cb HTTP/1.1

###

# Upload task image
POST http://localhost:3335/api/tasks/task/33/image HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JhN2IxZGE5OWUzMjYyNThmMmVhNjMiLCJlbWFpbCI6InVzZXIyMkB0ZXN0LmNvbSIsInJvbGUiOiJDdXN0b21lciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjczMTY3NDc4LCJleHAiOjE2NzMxNzEwNzh9.44Osg2UDEBID1P_LG7oUFaM_VKFv91KUKMTaAr_Zg7Q

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# download task image
GET http://localhost:3335/static/TLfZQbxGFhGLZewCxctlS.jpeg HTTP/1.1

###
