# Create a new task
POST http://localhost:3335/api/tasks/task HTTP/1.1
Content-Type: application/json

{
  "title": "Task's title veeeeeeeeeeeeeery long",
  "description": "Task's description Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla ",
  "categoryId": 1,
  "price": 100,
  "dueDate": "2023-02-22"
}

###

# Update task data
PATCH http://localhost:3335/api/tasks/task/5 HTTP/1.1
Content-Type: application/json

{
  "title": "Not Task's title veeeeeeeeeeeeeery long",
  "description": "Not Task's description Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla Bla "
}

###

# Get task by ID
GET http://localhost:3335/api/tasks/task/5 HTTP/1.1

###

# Delete task by Id
DELETE http://localhost:3335/api/tasks/task/5 HTTP/1.1

###

# Get new tasks
GET http://localhost:3335/api/tasks/new HTTP/1.1
###

# Get new tasks (filtered by categories, sorted and with pagination)
GET http://localhost:3335/api/tasks/new?cities=Москва,Владивосток&categories=2,1&limit=2&page=1&sort=popular HTTP/1.1
###

# Get new tasks (filtered by cities)
GET http://localhost:3335/api/tasks/new?cities=Москва HTTP/1.1
###

# Get new tasks (filtered by tags)
GET http://localhost:3335/api/tasks/new?tags=cleaning HTTP/1.1

###

# Change task's status
PATCH http://localhost:3335/api/tasks/task/43/status HTTP/1.1
Content-Type: application/json

{
  "status": "inProgress",
  "contractor": "63b325e47cd9f2573b2cf15d"
}

###

# Add comment to task
POST http://localhost:3335/api/tasks/task/5/comment HTTP/1.1
Content-Type: application/json

{
  "text": "Nice comment text!"
}

###

# Delete comment
DELETE http://localhost:3335/api/tasks/task/5/comment/5 HTTP/1.1

###

# Create new category
POST http://localhost:3335/api/tasks/category HTTP/1.1
Content-Type: application/json

{
  "name": "cleaning"
}

###

# Get all categories
GET http://localhost:3335/api/tasks/category HTTP/1.1

###

# Create new contractor's response
POST http://localhost:3335/api/tasks/task/5/response HTTP/1.1

###

# Get all responses by task
GET http://localhost:3335/api/tasks/task/5/response HTTP/1.1

###

# Add review to task
POST http://localhost:3335/api/tasks/review HTTP/1.1
Content-Type: application/json

{
  "text": "Nice doooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooone!",
  "contractor": "63b325e47cd9f2573b2cf15d",
  "rating": 5,
  "taskId": 43
}

###

# Get task contractor rating
GET http://localhost:3335/api/tasks/contractor/63b325e47cd9f2573b2cf15d/rating HTTP/1.1

###
